export const members = [
  { name: '群友 01', color: '#4ade80' },
  { name: '群友 02', color: '#38bdf8' },
  { name: '群友 03', color: '#facc15' },
  { name: '群友 04', color: '#fb7185' },
  { name: '群友 05', color: '#a78bfa' },
  { name: '群友 06', color: '#2dd4bf' },
  { name: '群友 07', color: '#f97316' },
  { name: '群友 08', color: '#e879f9' },
  { name: '群友 09', color: '#84cc16' },
  { name: '群友 10', color: '#60a5fa' },
  { name: '群友 11', color: '#f59e0b' },
  { name: '群友 12', color: '#34d399' },
  { name: '群友 13', color: '#c084fc' },
  { name: '群友 14', color: '#22d3ee' },
  { name: '群友 15', color: '#f472b6' },
  { name: '群友 16', color: '#a3e635' },
  { name: '群友 17', color: '#818cf8' },
  { name: '群友 18', color: '#fb923c' },
]

export const variants = [
  {
    id: 'forest',
    weight: 4,
    title: '群友房间',
    subtitle: 'Member Room',
    statsUnit: '位森林居民',
    statsDone: '位森林居民已全部现身',
    icon: '🌲',
    theme: 'forest',
    layout: 'grid',
    game: 'room',
    gameTitle: '群友房间',
    sceneLabel: '林间入口',
    sceneText: '树影把坐标藏进风里，点亮的头像会依次从雾中出现。',
    signalLabel: '林雾密度',
    signalValue: '72%',
    actionLabel: '森林暗号待唤醒',
    logTitle: '森林广播',
    logs: ['枝叶频道已打开', '正在校准群友坐标', '无妄之森欢迎回到据点'],
    particles: ['🍃', '🍂', '🌿', '🍁'],
    bubbles: ['🎮', '🌙', '⭐', '🎵', '✨', '🌿', '🍀', '🎯'],
    soundLabel: '森林白噪音',
    noise: { tone: 'brown', gain: 0.35 },
  },
  {
    id: 'firefly',
    weight: 3,
    title: '群友房间',
    subtitle: 'Member Room',
    statsUnit: '枚发光坐标',
    statsDone: '枚发光坐标已同步',
    icon: '✨',
    theme: 'firefly',
    layout: 'orbit',
    game: 'room',
    gameTitle: '群友房间',
    sceneLabel: '萤火轨道',
    sceneText: '成员围绕隐秘频道缓慢成环，发光坐标会按顺序同步。',
    signalLabel: '微光同步',
    signalValue: '88%',
    actionLabel: '萤火信号待释放',
    logTitle: '密会记录',
    logs: ['Hidden Channel 已接入', '萤火轨道稳定', '等待下一枚发光坐标'],
    particles: ['✨', '💫', '⭐', '🌙'],
    bubbles: ['✨', '💫', '🌙', '🎵', '⭐', '💎'],
    soundLabel: '微光白噪音',
    noise: { tone: 'pink', gain: 0.25 },
  },
  {
    id: 'rain',
    weight: 2,
    title: '群友房间',
    subtitle: 'Member Room',
    statsUnit: '位避雨来客',
    statsDone: '位避雨来客已入座',
    icon: '☔',
    theme: 'rain',
    layout: 'lounge',
    game: 'room',
    gameTitle: '群友房间',
    sceneLabel: '窗边卡座',
    sceneText: '雨声把大厅压低，前三位来客先在暖光下落座。',
    signalLabel: '室内温度',
    signalValue: '24°C',
    actionLabel: '今日小纸条待派发',
    logTitle: '小屋留言',
    logs: ['门口雨伞已收纳', '热饮正在准备', '避雨来客陆续入座'],
    particles: ['╱', '╲', '╱', '╲'],
    bubbles: ['☔', '☕', '🎮', '🌧️', '💤', '🎵'],
    soundLabel: '雨声白噪音',
    noise: { tone: 'white', gain: 0.18 },
  },
  {
    id: 'arcade',
    weight: 1,
    title: '群友房间',
    subtitle: 'Member Room',
    statsUnit: '位隐藏玩家',
    statsDone: '位隐藏玩家已 Ready',
    icon: '▣',
    theme: 'arcade',
    layout: 'ticker',
    game: 'room',
    gameTitle: '群友房间',
    sceneLabel: '隐藏关卡',
    sceneText: '像素闸门启动，玩家名单会像街机跑马灯一样刷过。',
    signalLabel: 'Combo',
    signalValue: 'x18',
    actionLabel: '奖励图标待结算',
    logTitle: '街机终端',
    logs: ['INSERT COIN', 'Bonus Stage Ready', '隐藏玩家加入队列'],
    particles: ['◆', '◇', '■', '□'],
    bubbles: ['🎮', '🕹️', '⚡', '💎', '🚀', '🏆'],
    soundLabel: '电子白噪音',
    noise: { tone: 'bit', gain: 0.16 },
  },
  {
    id: 'stargate',
    weight: 2,
    title: '群友房间',
    subtitle: 'Member Room',
    statsUnit: '枚跃迁信标',
    statsDone: '枚跃迁信标已点亮',
    icon: '✦',
    theme: 'stargate',
    layout: 'constellation',
    game: 'room',
    gameTitle: '群友房间',
    sceneLabel: '跃迁队列',
    sceneText: '信标散落成星图，连线亮起后就能穿过星门。',
    signalLabel: '跃迁充能',
    signalValue: '64%',
    actionLabel: '星图回波待发射',
    logTitle: '星门调度',
    logs: ['星门环已锁定', '跃迁信标逐枚点亮', '等待安全窗口'],
    particles: ['✦', '✧', '·', '×'],
    bubbles: ['🚀', '✦', '🌌', '🛰️', '💫', '⭐'],
    soundLabel: '星际白噪音',
    noise: { tone: 'pink', gain: 0.2 },
  },
  {
    id: 'library',
    weight: 2,
    title: '群友房间',
    subtitle: 'Member Room',
    statsUnit: '份借阅记录',
    statsDone: '份借阅记录已归档',
    icon: '▤',
    theme: 'library',
    layout: 'shelf',
    game: 'room',
    gameTitle: '群友房间',
    sceneLabel: '借阅柜台',
    sceneText: '每位成员都是一份档案，归档后会在书架上留下微光索引。',
    signalLabel: '归档进度',
    signalValue: '91%',
    actionLabel: '索引书签待归档',
    logTitle: '书库索引',
    logs: ['Archive Room 已静音', '借阅记录正在排序', '索引页已写入星标'],
    particles: ['□', '◇', '·', '▫'],
    bubbles: ['📖', '☕', '✨', '📝', '💭', '⭐'],
    soundLabel: '书页白噪音',
    noise: { tone: 'brown', gain: 0.18 },
  },
  {
    id: 'aurora',
    weight: 2,
    title: '群友房间',
    subtitle: 'Member Room',
    statsUnit: '道回声',
    statsDone: '道回声已汇入回廊',
    icon: '◇',
    theme: 'aurora',
    layout: 'ribbon',
    game: 'room',
    gameTitle: '群友房间',
    sceneLabel: '镜面回廊',
    sceneText: '极光像丝带一样穿过成员之间，回声会沿着中线折返。',
    signalLabel: '折射强度',
    signalValue: '79%',
    actionLabel: '极光回声待折返',
    logTitle: '回廊回声',
    logs: ['镜面角度已校准', '极光带进入回廊', '回声正在汇入主线'],
    particles: ['◇', '◆', '✧', '·'],
    bubbles: ['🌈', '💎', '✨', '💫', '🎵', '🌙'],
    soundLabel: '极光白噪音',
    noise: { tone: 'pink', gain: 0.22 },
  },
  {
    id: 'kitchen',
    weight: 1,
    title: '群友房间',
    subtitle: 'Member Room',
    statsUnit: '份夜宵订单',
    statsDone: '份夜宵订单已出餐',
    icon: '☕',
    theme: 'kitchen',
    layout: 'lounge',
    game: 'room',
    gameTitle: '群友房间',
    sceneLabel: '夜宵窗口',
    sceneText: '灶台亮着一圈暖光，订单从深夜频道一份份滑进来。',
    signalLabel: '出餐火候',
    signalValue: '刚好',
    actionLabel: '夜宵贴纸待出餐',
    logTitle: '灶台小票',
    logs: ['Midnight Mode 已开火', '夜宵订单排队中', '最后一份留给迟到的人'],
    particles: ['·', '∴', '°', '✧'],
    bubbles: ['☕', '🍜', '🎮', '✨', '😴', '🎵'],
    soundLabel: '暖炉白噪音',
    noise: { tone: 'brown', gain: 0.2 },
  },
]
