// 首页新增区块的中英文文案；产品链接复用 App.vue 中的客户端数据。
export const showcaseContent = {
  zh: {
    products: '产品矩阵',
    productsSubtitle: '电脑安装 Sunshine 服务端，再为你的设备选择 Moonlight 客户端。',
    host: '串流服务端',
    hostDescription: '将游戏电脑变成串流主机，集成 HDR 支持、虚拟显示器与控制面板。',
    getHost: '下载服务端',
    client: '生态客户端',
    getClient: '查看客户端',
    clientDescriptions: {
      'android-vplus': '在 Android 手机、平板和电视上连接游戏电脑。',
      'harmonyos-vplus': '面向 HarmonyOS NEXT 设备的游戏串流客户端。',
      'moonlight-pc': '在 Windows、macOS 和 Linux 电脑上接收串流。',
      'macos-enhanced': '社区维护的 macOS 增强客户端。',
      voidlink: '在 iPhone 和 iPad 上体验电脑游戏。',
    },
    note: '生态客户端包含社区项目，具体功能和发行信息以各项目页面为准。',
    stories: '流梦现场',
    storiesSubtitle: '了解开发进展，体验新功能，与社区一起探索串流玩法。',
    read: '了解更多',
    items: [
      { category: '功能演示', title: '音频触觉体验', description: '打开交互演示，探索声音与振动之间的联系。', url: '/audio-haptics-demo.html' },
      { category: '开发手记', title: '杜比视界：从元数据到原生输出', description: '记录联想“无极”平板黑屏的排查，以及 Profile 8.1 与 8.4 的实机验证。', url: '/docs/dolby-vision-dev-journal-zh.html' },
      { category: '研发进展 · 2026.07.23', title: '手柄支持与自研触觉 SDK', description: '了解触觉 SDK 的技术方向与设备支持计划。', url: '/docs/razer-haptics-sdk-announcement-zh.html' },
      { category: '版本动态', title: 'Sunshine 更新日志', description: '查看新版本的功能变化、修复内容和发行说明。', url: 'https://github.com/AlkaidLab/foundation-sunshine/releases' },
      { category: '玩家社区', title: '一起交流串流玩法', description: '加入 QQ 交流群，分享设备配置、使用心得与建议。', url: 'https://qm.qq.com/cgi-bin/qm/qr?k=5qnkzSaLIrIaU4FvumftZH_6Hg7fUuLD&jump_from=webapi' },
    ],
  },
  en: {
    products: 'Product ecosystem',
    productsSubtitle: 'Install Sunshine on your gaming PC, then choose a Moonlight client for your device.',
    host: 'Streaming host',
    hostDescription: 'Turn your gaming PC into a streaming host with HDR support, virtual displays and a control panel.',
    getHost: 'Download host',
    client: 'Ecosystem client',
    getClient: 'View client',
    clientDescriptions: {
      'android-vplus': 'Connect to your gaming PC from an Android phone, tablet or TV.',
      'harmonyos-vplus': 'A game streaming client for HarmonyOS NEXT devices.',
      'moonlight-pc': 'Receive streams on Windows, macOS and Linux computers.',
      'macos-enhanced': 'A community-maintained enhanced client for macOS.',
      voidlink: 'Enjoy PC games on iPhone and iPad.',
    },
    note: 'The ecosystem includes community projects. See each project for features and releases.',
    stories: 'Inside Alkaid',
    storiesSubtitle: 'Follow development, try new features and explore streaming with the community.',
    read: 'Learn more',
    items: [
      { category: 'Interactive demo', title: 'Audio haptics', description: 'Explore the connection between sound and vibration with an interactive demo.', url: '/audio-haptics-demo.html' },
      { category: 'Dev journal', title: 'Dolby Vision: from metadata to native output', description: 'Tracing a Lenovo tablet black screen and validating native Profile 8.1 and 8.4 output. Article in Chinese.', url: '/docs/dolby-vision-dev-journal-zh.html' },
      { category: 'Development · 2026.07.23', title: 'Controller support & our haptics SDK', description: 'Read about our technical direction and device support plans. Article in Chinese.', url: '/docs/razer-haptics-sdk-announcement-zh.html' },
      { category: 'Releases', title: 'Sunshine release notes', description: 'Discover features, fixes and release notes for new versions.', url: 'https://github.com/AlkaidLab/foundation-sunshine/releases' },
      { category: 'Community', title: 'Share your streaming experience', description: 'Join our QQ community to share device setups, tips and feedback.', url: 'https://qm.qq.com/cgi-bin/qm/qr?k=5qnkzSaLIrIaU4FvumftZH_6Hg7fUuLD&jump_from=webapi' },
    ],
  },
}
